//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCOME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public int IdCategoria { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
